apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: server-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-api-deployment
      instance: "1"
  template:
    metadata:
      labels:
        app: server-api-deployment
        instance: "1"
    spec:
      containers:
      - name: server-api
        image: server-api:1.0
        env:
        - name: SERVER_API_SERVICE_ID
          value: "1"
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: server-api-service-1
spec:
  type: NodePort
  selector:
    app: server-api-deployment
    instance: "1"
  ports:
    - name: http
      protocol: TCP
      port: 31501
      targetPort: 5000
      nodePort: 31501
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: server-api-service-2
spec:
  type: NodePort
  selector:
    app: server-api-deployment
    instance: "1"
  ports:
    - name: http
      protocol: TCP
      port: 31502
      targetPort: 5000
      nodePort: 31502
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: server-api-service-3
spec:
  type: NodePort
  selector:
    app: server-api-deployment
    instance: "1"
  ports:
    - name: http
      protocol: TCP
      port: 31503
      targetPort: 5000
      nodePort: 31503
---
apiVersion: v1
kind: Service
metadata:
  name: server-api-service-loadbalancer-1
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 31500
    targetPort: 5000
  selector:
    app: server-api-deployment
    instance: "1"